export const countries = [
  { label: "Afghanistan", value: "AF", callingCode: "+93" },
  { label: "Albania", value: "AL", callingCode: "+355" },
  { label: "Algeria", value: "DZ", callingCode: "+213" },
  { label: "Andorra", value: "AD", callingCode: "+376" },
  { label: "Angola", value: "AO", callingCode: "+244" },
  { label: "Argentina", value: "AR", callingCode: "+54" },
  { label: "Armenia", value: "AM", callingCode: "+374" },
  { label: "Australia", value: "AU", callingCode: "+61" },
  { label: "Austria", value: "AT", callingCode: "+43" },
  { label: "Azerbaijan", value: "AZ", callingCode: "+994" },
  { label: "Bahamas", value: "BS", callingCode: "+1-242" },
  { label: "Bahrain", value: "BH", callingCode: "+973" },
  { label: "Bangladesh", value: "BD", callingCode: "+880" },
  { label: "Barbados", value: "BB", callingCode: "+1-246" },
  { label: "Belarus", value: "BY", callingCode: "+375" },
  { label: "Belgium", value: "BE", callingCode: "+32" },
  { label: "Belize", value: "BZ", callingCode: "+501" },
  { label: "Benin", value: "BJ", callingCode: "+229" },
  { label: "Bhutan", value: "BT", callingCode: "+975" },
  { label: "Bolivia", value: "BO", callingCode: "+591" },
  { label: "Bosnia and Herzegovina", value: "BA", callingCode: "+387" },
  { label: "Botswana", value: "BW", callingCode: "+267" },
  { label: "Brazil", value: "BR", callingCode: "+55" },
  { label: "Brunei", value: "BN", callingCode: "+673" },
  { label: "Bulgaria", value: "BG", callingCode: "+359" },
  { label: "Burkina Faso", value: "BF", callingCode: "+226" },
  { label: "Burundi", value: "BI", callingCode: "+257" },
  { label: "Cabo Verde", value: "CV", callingCode: "+238" },
  { label: "Cambodia", value: "KH", callingCode: "+855" },
  { label: "Cameroon", value: "CM", callingCode: "+237" },
  { label: "Canada", value: "CA", callingCode: "+1" },
  { label: "Central African Republic", value: "CF", callingCode: "+236" },
  { label: "Chad", value: "TD", callingCode: "+235" },
  { label: "Chile", value: "CL", callingCode: "+56" },
  { label: "China", value: "CN", callingCode: "+86" },
  { label: "Colombia", value: "CO", callingCode: "+57" },
  { label: "Comoros", value: "KM", callingCode: "+269" },
  {
    label: "Congo, Democratic Republic of the",
    value: "CD",
    callingCode: "+243",
  },
  { label: "Congo, Republic of the", value: "CG", callingCode: "+242" },
  { label: "Costa Rica", value: "CR", callingCode: "+506" },
  { label: "Croatia", value: "HR", callingCode: "+385" },
  { label: "Cuba", value: "CU", callingCode: "+53" },
  { label: "Cyprus", value: "CY", callingCode: "+357" },
  { label: "Czech Republic", value: "CZ", callingCode: "+420" },
  { label: "Denmark", value: "DK", callingCode: "+45" },
  { label: "Djibouti", value: "DJ", callingCode: "+253" },
  { label: "Dominica", value: "DM", callingCode: "+1-767" },
  { label: "Dominican Republic", value: "DO", callingCode: "+1-809" },
  { label: "East Timor", value: "TL", callingCode: "+670" },
  { label: "Ecuador", value: "EC", callingCode: "+593" },
  { label: "Egypt", value: "EG", callingCode: "+20" },
  { label: "El Salvador", value: "SV", callingCode: "+503" },
  { label: "Equatorial Guinea", value: "GQ", callingCode: "+240" },
  { label: "Eritrea", value: "ER", callingCode: "+291" },
  { label: "Estonia", value: "EE", callingCode: "+372" },
  { label: "Eswatini", value: "SZ", callingCode: "+268" },
  { label: "Ethiopia", value: "ET", callingCode: "+251" },
  { label: "Fiji", value: "FJ", callingCode: "+679" },
  { label: "Finland", value: "FI", callingCode: "+358" },
  { label: "France", value: "FR", callingCode: "+33" },
  { label: "Gabon", value: "GA", callingCode: "+241" },
  { label: "Gambia", value: "GM", callingCode: "+220" },
  { label: "Georgia", value: "GE", callingCode: "+995" },
  { label: "Germany", value: "DE", callingCode: "+49" },
  { label: "Ghana", value: "GH", callingCode: "+233" },
  { label: "Greece", value: "GR", callingCode: "+30" },
  { label: "Grenada", value: "GD", callingCode: "+1-473" },
  { label: "Guatemala", value: "GT", callingCode: "+502" },
  { label: "Guinea", value: "GN", callingCode: "+224" },
  { label: "Guinea-Bissau", value: "GW", callingCode: "+245" },
  { label: "Guyana", value: "GY", callingCode: "+592" },
  { label: "Haiti", value: "HT", callingCode: "+509" },
  { label: "Honduras", value: "HN", callingCode: "+504" },
  { label: "Hungary", value: "HU", callingCode: "+36" },
  { label: "Iceland", value: "IS", callingCode: "+354" },
  { label: "India", value: "IN", callingCode: "+91" },
  { label: "Indonesia", value: "ID", callingCode: "+62" },
  { label: "Iran", value: "IR", callingCode: "+98" },
  { label: "Iraq", value: "IQ", callingCode: "+964" },
  { label: "Ireland", value: "IE", callingCode: "+353" },
  { label: "Israel", value: "IL", callingCode: "+972" },
  { label: "Italy", value: "IT", callingCode: "+39" },
  { label: "Jamaica", value: "JM", callingCode: "+1-876" },
  { label: "Japan", value: "JP", callingCode: "+81" },
  { label: "Jordan", value: "JO", callingCode: "+962" },
  { label: "Kazakhstan", value: "KZ", callingCode: "+7" },
  { label: "Kenya", value: "KE", callingCode: "+254" },
  { label: "Kiribati", value: "KI", callingCode: "+686" },
  { label: "Korea, North", value: "KP", callingCode: "+850" },
  { label: "Korea, South", value: "KR", callingCode: "+82" },
  { label: "Kuwait", value: "KW", callingCode: "+965" },
  { label: "Kyrgyzstan", value: "KG", callingCode: "+996" },
  { label: "Laos", value: "LA", callingCode: "+856" },
  { label: "Latvia", value: "LV", callingCode: "+371" },
  { label: "Lebanon", value: "LB", callingCode: "+961" },
  { label: "Lesotho", value: "LS", callingCode: "+266" },
  { label: "Liberia", value: "LR", callingCode: "+231" },
  { label: "Libya", value: "LY", callingCode: "+218" },
  { label: "Liechtenstein", value: "LI", callingCode: "+423" },
  { label: "Lithuania", value: "LT", callingCode: "+370" },
  { label: "Luxembourg", value: "LU", callingCode: "+352" },
  { label: "Madagascar", value: "MG", callingCode: "+261" },
  { label: "Malawi", value: "MW", callingCode: "+265" },
  { label: "Malaysia", value: "MY", callingCode: "+60" },
  { label: "Maldives", value: "MV", callingCode: "+960" },
  { label: "Mali", value: "ML", callingCode: "+223" },
  { label: "Malta", value: "MT", callingCode: "+356" },
  { label: "Marshall Islands", value: "MH", callingCode: "+692" },
  { label: "Mauritania", value: "MR", callingCode: "+222" },
  { label: "Mauritius", value: "MU", callingCode: "+230" },
  { label: "Mexico", value: "MX", callingCode: "+52" },
  { label: "Micronesia", value: "FM", callingCode: "+691" },
  { label: "Moldova", value: "MD", callingCode: "+373" },
  { label: "Monaco", value: "MC", callingCode: "+377" },
  { label: "Mongolia", value: "MN", callingCode: "+976" },
  { label: "Montenegro", value: "ME", callingCode: "+382" },
  { label: "Morocco", value: "MA", callingCode: "+212" },
  { label: "Mozambique", value: "MZ", callingCode: "+258" },
  { label: "Myanmar", value: "MM", callingCode: "+95" },
  { label: "Namibia", value: "NA", callingCode: "+264" },
  { label: "Nauru", value: "NR", callingCode: "+674" },
  { label: "Nepal", value: "NP", callingCode: "+977" },
  { label: "Netherlands", value: "NL", callingCode: "+31" },
  { label: "New Zealand", value: "NZ", callingCode: "+64" },
  { label: "Nicaragua", value: "NI", callingCode: "+505" },
  { label: "Niger", value: "NE", callingCode: "+227" },
  { label: "Nigeria", value: "NG", callingCode: "+234" },
  { label: "North Macedonia", value: "MK", callingCode: "+389" },
  { label: "Norway", value: "NO", callingCode: "+47" },
  { label: "Oman", value: "OM", callingCode: "+968" },
  { label: "Pakistan", value: "PK", callingCode: "+92" },
  { label: "Palau", value: "PW", callingCode: "+680" },
  { label: "Panama", value: "PA", callingCode: "+507" },
  { label: "Papua New Guinea", value: "PG", callingCode: "+675" },
  { label: "Paraguay", value: "PY", callingCode: "+595" },
  { label: "Peru", value: "PE", callingCode: "+51" },
  { label: "Philippines", value: "PH", callingCode: "+63" },
  { label: "Poland", value: "PL", callingCode: "+48" },
  { label: "Portugal", value: "PT", callingCode: "+351" },
  { label: "Qatar", value: "QA", callingCode: "+974" },
  { label: "Romania", value: "RO", callingCode: "+40" },
  { label: "Russia", value: "RU", callingCode: "+7" },
  { label: "Rwanda", value: "RW", callingCode: "+250" },
  { label: "Saint Kitts and Nevis", value: "KN", callingCode: "+1-869" },
  { label: "Saint Lucia", value: "LC", callingCode: "+1-758" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "VC",
    callingCode: "+1-784",
  },
  { label: "Samoa", value: "WS", callingCode: "+685" },
  { label: "San Marino", value: "SM", callingCode: "+378" },
  { label: "Sao Tome and Principe", value: "ST", callingCode: "+239" },
  { label: "Saudi Arabia", value: "SA", callingCode: "+966" },
  { label: "Senegal", value: "SN", callingCode: "+221" },
  { label: "Serbia", value: "RS", callingCode: "+381" },
  { label: "Seychelles", value: "SC", callingCode: "+248" },
  { label: "Sierra Leone", value: "SL", callingCode: "+232" },
  { label: "Singapore", value: "SG", callingCode: "+65" },
  { label: "Slovakia", value: "SK", callingCode: "+421" },
  { label: "Slovenia", value: "SI", callingCode: "+386" },
  { label: "Solomon Islands", value: "SB", callingCode: "+677" },
  { label: "Somalia", value: "SO", callingCode: "+252" },
  { label: "South Africa", value: "ZA", callingCode: "+27" },
  { label: "Spain", value: "ES", callingCode: "+34" },
  { label: "Sri Lanka", value: "LK", callingCode: "+94" },
  { label: "Sudan", value: "SD", callingCode: "+249" },
  { label: "Suriname", value: "SR", callingCode: "+597" },
  { label: "Sweden", value: "SE", callingCode: "+46" },
  { label: "Switzerland", value: "CH", callingCode: "+41" },
  { label: "Syria", value: "SY", callingCode: "+963" },
  { label: "Taiwan", value: "TW", callingCode: "+886" },
  { label: "Tajikistan", value: "TJ", callingCode: "+992" },
  { label: "Tanzania", value: "TZ", callingCode: "+255" },
  { label: "Thailand", value: "TH", callingCode: "+66" },
  { label: "Togo", value: "TG", callingCode: "+228" },
  { label: "Tonga", value: "TO", callingCode: "+676" },
  { label: "Trinidad and Tobago", value: "TT", callingCode: "+1-868" },
  { label: "Tunisia", value: "TN", callingCode: "+216" },
  { label: "Turkey", value: "TR", callingCode: "+90" },
  { label: "Turkmenistan", value: "TM", callingCode: "+993" },
  { label: "Tuvalu", value: "TV", callingCode: "+688" },
  { label: "Uganda", value: "UG", callingCode: "+256" },
  { label: "Ukraine", value: "UA", callingCode: "+380" },
  { label: "United Arab Emirates", value: "AE", callingCode: "+971" },
  { label: "United Kingdom", value: "GB", callingCode: "+44" },
  { label: "United States", value: "US", callingCode: "+1" },
  { label: "Uruguay", value: "UY", callingCode: "+598" },
  { label: "Uzbekistan", value: "UZ", callingCode: "+998" },
  { label: "Vanuatu", value: "VU", callingCode: "+678" },
  { label: "Vatican City", value: "VA", callingCode: "+379" },
  { label: "Venezuela", value: "VE", callingCode: "+58" },
  { label: "Vietnam", value: "VN", callingCode: "+84" },
  { label: "Yemen", value: "YE", callingCode: "+967" },
  { label: "Zambia", value: "ZM", callingCode: "+260" },
  { label: "Zimbabwe", value: "ZW", callingCode: "+263" },
];
